# Maintainer: you <you@example.com>
# Package: AUR-GAME (aur-game)
# Generated by automation to match your other repositories — review before publishing to AUR
pkgname=aur-game
pkgver=0.1.0
pkgrel=1
pkgdesc="Agecoin TG-game — Telegram webapp backend"
arch=(any)
url="https://github.com/LEON1KING1/Agecoin_app"
license=(custom)
dependencies=(php php-mysqli php-curl)
source=("${url}/archive/refs/tags/v${pkgver}.tar.gz")
sha256sums=('SKIP')

prepare() {
  cd "$srcdir"
  # nothing to build; keep original layout
}

package() {
  cd "$srcdir/$(basename "${url}")-v${pkgver}"
  install -d "$pkgdir/usr/share/$pkgname"
  cp -a . "$pkgdir/usr/share/$pkgname/"

  install -d "$pkgdir/usr/share/doc/$pkgname"
  [[ -f README.md ]] && install -m644 README.md "$pkgdir/usr/share/doc/$pkgname/README.md"
  [[ -f LICENSE ]] && install -m644 LICENSE "$pkgdir/usr/share/doc/$pkgname/LICENSE"

  # example systemd snippet (no unit provided by upstream)
  install -d "$pkgdir/usr/lib/$pkgname"
}

# vim: ft=sh
